spring:
  application:
    name: marketlens-api

  profiles:
    active: dev

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

openrouter:
  api:
    key: ${OPENROUTER_API_KEY}
    url: "https://openrouter.ai/api/v1/chat/completions"
    model: "tencent/hy3:free"