spring:
  application:
    name: marketlens-api

  profiles:
    active: dev

server:
  port: 9090

openrouter:
  api:
    key: ${OPENROUTER_API_KEY:}
    url: "https://openrouter.ai/api/v1/chat/completions"
    model: "openrouter/free"
